# time_graph_bucketed.py — Signals grouped in 30-minute intervals

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime

FILE = "backtest_opening_range.csv"

def plot_bucketed_signals():
    df = pd.read_csv(FILE)

    if "time" not in df.columns:
        print("❌ 'time' column not found in backtest file.")
        return

    # Convert time
    df["time"] = pd.to_datetime(df["time"], format="%H:%M:%S", errors="coerce").dt.time
    df = df.dropna(subset=["time"])

    # Convert to datetime for easier bucketing
    df["datetime"] = pd.to_datetime(df["time"].astype(str))

    # Create 30-minute buckets
    df["bucket"] = df["datetime"].dt.floor("30min").dt.strftime("%H:%M")

    # Count signals per bucket
    counts = df.groupby("bucket").size().reset_index(name="count")

    # Sort by time
    counts["datetime"] = pd.to_datetime(counts["bucket"], format="%H:%M")
    counts = counts.sort_values("datetime")

    # Plot
    plt.figure(figsize=(10, 5))
    plt.bar(counts["bucket"], counts["count"], color="#5AA9E6", alpha=0.8)

    plt.title("Signals Generated by 30-Minute Time Buckets", fontsize=14, weight="bold")
    plt.xlabel("Time Bucket (HH:MM)", fontsize=12)
    plt.ylabel("Number of Signals", fontsize=12)

    plt.xticks(rotation=45, ha="right")
    plt.grid(axis="y", linestyle="--", alpha=0.4)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    plot_bucketed_signals()